# Generated by Django 2.1.7 on 2019-05-08 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_development', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.IntegerField()),
                ('startdate', models.DateField(auto_now_add=True)),
                ('enddate', models.DateField()),
                ('product_type', models.IntegerField()),
                ('region', models.IntegerField()),
                ('phonenumber', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Offer Element',
            },
        ),
    ]
