# Generated by Django 2.0.4 on 2019-05-22 19:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('service_development', '0005_auto_20190522_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='enddate',
            field=models.DateField(default=datetime.datetime(2019, 6, 21, 19, 43, 55, 821173, tzinfo=utc)),
        ),
    ]
