# Generated by Django 2.1.7 on 2019-05-13 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_development', '0008_offer_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='description',
            new_name='voice_label',
        ),
    ]
