# Generated by Django 2.0.4 on 2019-05-15 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_development', '0009_auto_20190513_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='callsession',
            name='_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service_development.Product'),
        ),
        migrations.AddField(
            model_name='callsession',
            name='_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service_development.Region'),
        ),
    ]
